# Generated by Django 4.2.7 on 2023-12-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=200)),
                ('premio', models.PositiveIntegerField()),
                ('detalle_dias', models.CharField(max_length=50)),
                ('cobertura', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='imgDestinos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'YTOT',
            },
        ),
    ]
