# Generated by Django 4.2.7 on 2023-12-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_destinos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='cobertura',
            field=models.CharField(max_length=20, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='destino',
            field=models.CharField(max_length=50, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='detalle',
            field=models.CharField(max_length=200, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='detalle_dias',
            field=models.CharField(max_length=50, verbose_name='Estadía'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='imagen',
            field=models.ImageField(upload_to='imgDestinos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='premio',
            field=models.PositiveIntegerField(verbose_name='Premio'),
        ),
    ]
