# Generated by Django 4.2.7 on 2023-12-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_destinos_cobertura_alter_destinos_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinos',
            name='is_active',
        ),
    ]
