# Generated by Django 4.2.7 on 2023-12-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_destinos_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='premio',
            field=models.CharField(max_length=10, verbose_name='Premio'),
        ),
    ]
