# Generated by Django 4.2.7 on 2023-12-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_destinos_premio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='imagen',
            field=models.ImageField(upload_to='imgDestinos/', verbose_name='Photo'),
        ),
    ]
