# Generated by Django 4.2.7 on 2023-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_destinos_imagen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destinos',
            table='Tabladestinos',
        ),
    ]
