# Generated by Django 4.2.7 on 2023-12-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_destinos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destinos',
            table='destinos',
        ),
    ]
