# Generated by Django 4.2.7 on 2023-12-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_destinos_cobertura_alter_destinos_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('destinos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.destinos')),
            ],
            bases=('api.destinos',),
        ),
    ]
